theme: jekyll-theme-cayman
title: "Recursive algorithms with Python"
description: "This repository shows the implementation of the most common recursive algorithms"
author: "Ramses Alexander Coraspe Valdez"
