theme: jekyll-theme-cayman
title: "Recursive algorithms with Python"
description: "The repository contains basic experiments using machine learning algorithms with python"
author: "Ramses Alexander Coraspe Valdez"
